# config/packages/easy_admin.yaml
easy_admin:
    formats:
        date: 'd/m/Y'
    entities:
        User:
            class: App\Entity\User
            list: 
                fields: ['username','groupe','DateNaissance','prenom','nom','CategorieAge','zoneArbitre']
            form:
                fields:
                    - {property : 'username'}
                    - {property : 'groupe'}
                    - {property : 'Nom'}
                    - {property : 'prenom'}
                    - {property : 'CategorieAge'}
                    - {property : 'zoneArbitre'}




                
        Entrainement:
            class: App\Entity\Entrainement
        Competitions:
            class: App\Entity\Competitions
            list: 
                fields: ['name','dateStart','dateEnd','participants','CategorieAge','zoneArbitre']
            form:
                fields:
                    - {property : 'name'}
                    - {property : 'dateStart'}
                    - {property : 'dateEnd'}
                    - {property : 'participants'}
                    - {property : 'CategorieAge'}
                    - {property : 'zoneArbitre'}
                    

                    

        CompetitionsUser:
            class: App\Entity\CompetitionsUser
        EntrainementUser:
            class: App\Entity\EntrainementUser
        Groupe:
            class: App\Entity\Groupe
            form:
                fields:
                - {property : 'nom'}
                - {property : 'users'}

        Lecon:
            class: App\Entity\Lecon
        
        CategorieAge:
            class: App\Entity\CategorieAge
            form:
                fields:
                - {property : 'libelle'}

        Arbitre:
            class: App\Entity\Arbitre


      