# config/packages/easy_admin.yaml
easy_admin:
    formats:
        date: 'd/m/Y'
    entities:
        User:
            class: App\Entity\User
            list: 
                fields: ['Id','username','groupe','DateNaissance','nom','prenom','CategorieAge']
            form:
                fields:
                    - {property : 'username'}
                    - {property : 'groupe'}
                    - {property : 'Nom'}
                    - {property : 'prenom'}
                    - {property : 'CategorieAge'}


                
        Entrainement:
            class: App\Entity\Entrainement
        Competitions:
            class: App\Entity\Competitions
            list: 
                fields: ['id','name','dateStart','dateEnd','participants','CategorieAge']
            form:
                fields:
                    - {property : 'name'}
                    - {property : 'dateStart'}
                    - {property : 'dateEnd'}
                    - {property : 'participants'}
                    - {property : 'CategorieAge'}
                    - {property : 'arme'}
                    - {property : 'blason'}

                    

        CompetitionsUser:
            class: App\Entity\CompetitionsUser
        EntrainementUser:
            class: App\Entity\EntrainementUser
        Groupe:
            class: App\Entity\Groupe
            form:
                fields:
                - {property : 'nom'}
                - {property : 'users'}

        Lecon:
            class: App\Entity\Lecon
        UserArbitre:
            class: App\Entity\UserArbitre
        
        CategorieAge:
            class: App\Entity\CategorieAge
            form:
                fields:
                - {property : 'libelle'}


      