# config/packages/easy_admin.yaml
easy_admin:
    formats:
        date: 'd/m/Y'
    entities:
        User:
            class: App\Entity\User
            list: 
                fields: ['Id','username','groupe','DateNaissance','role']
            form:
                fields:
                    - {property : 'username'}
                    - {property : 'groupe'}
                    - {property : 'role'}

                
        Entrainement:
            class: App\Entity\Entrainement
        Competitions:
            class: App\Entity\Competitions
        CompetitionsUser:
            class: App\Entity\CompetitionsUser
        EntrainementUser:
            class: App\Entity\EntrainementUser
        Groupe:
            class: App\Entity\Groupe
            form:
                fields:
                - {property : 'nom'}
                - {property : 'users'}

        Lecon:
            class: App\Entity\Lecon
        UserArbitre:
            class: App\Entity\UserArbitre
        
