# config/packages/easy_admin.yaml
easy_admin:
    entities:
        User:
            class: App\Entity\User
        Entrainement:
            class: App\Entity\Entrainement
        Competitions:
            class: App\Entity\Competitions